### ISSUE TITLE
Dragging causes wrong view to receive input 

### ISSUE THREAD

**Issue by Snektron** [riverwm/river#466]
Some programs support dragging parts (for example tabs) of it to other windows of the program. When this is done under River, i can see that the view focus changes as the indicator moves to the target of the view, but when i release the drag and press on a key, input appears on the old view.

To reproduce:
* Open two instances of a program which supports dragging parts, for example Firefox.
* Open an extra tab on one Firefox instance, drag it to the other instance. This focuses the other instance.
* Type something, at which point the result appears on the original Firefox instance rather than the one focused after dragging.

The problem appears regardless of whether the two instances are on the same or on different outputs.

This also manifests itself with Sublime Text and Chromium, though in the case of the latter Chromium spawns a new window during the dragging process so it only reproduces when you perform the drag really fast.

River version: 0.1.0

**Comment by ifreund** [comment]
Ah I see, this only reproduces with `focus-follows-cursor` enabled.

**Comment by ifreund** [comment]
Should be fixed by 9212ac89fa4c1a540798143a33dd3e331c31a76c

**Comment by Snektron** [comment]
Unfortunately it seems that this doesn't completely resolve the problem. It seems that now i also lose pointer input, as well as keyboard input, to the window that should be focused. It occurs in the same situation as before.

> Ah I see, this only reproduces with focus-follows-cursor enabled.

Sorry, i forgot to mention that. I have `focus-follows-cursor` set to `normal`.

**Comment by ifreund** [comment]
@Snektron thanks, it appears that my commit fixed the keyboard issue (at least as far as I can tell) but caused problems with pointer input on firefox and a gtk3 demo client using drag and drop. 

I believe I've either worked around a gtk bug or fixed a river bug in #476.

**Comment by ifreund** [comment]
This second bug is fixed by this wlroots patch which has been merged today: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3364. I'll implement a workaround for this as a stop-gap until the next wlroots release however.

**Comment by ifreund** [comment]
Workaround implemented in bd70c010e9861df105db7cf25f57762a661873ec
