### ISSUE TITLE
Toggling fullscreen on fullscreen SDL apps causes buggy behavior and may crash river

### ISSUE THREAD

**Issue by vainiovano** [riverwm/river#521]
Tested with [DCSS](https://crawl.develz.org/) and [DDNet client](https://ddnet.tw/). When the game is unfullscreened with Super+F, it enters a "partial fullscreen" state: it is rendered like a fullscreen window and works like a fullscreen window, but its configured size matches the windowed size:
![image](https://user-images.githubusercontent.com/16741932/151665187-58da3d76-6842-4f4f-8a06-8eb4e60ab9b8.png)

SDL is spamming the compositor with `set_fullscreen` requests when in this "partial fullscreen" state; this indicates that `XDG_TOPLEVEL_STATE_FULLSCREEN` is not set:
```
[2438127.635] wl_callback@22.done(18348)
[2438128.183]  -> wl_surface@18.attach(wl_buffer@27, 0, 0)
[2438128.206]  -> wl_surface@18.damage(0, 0, 2147483647, 2147483647)
[2438128.311]  -> wl_surface@18.commit()
[2438128.320]  -> wl_display@1.sync(new id wl_callback@22)
[2438129.189] wl_display@1.delete_id(32)
[2438129.209] wl_display@1.delete_id(22)
[2438129.220] xdg_toplevel@24.configure(815, 739, array[8])
[2438129.238]  -> xdg_toplevel@24.set_min_size(0, 0)
[2438129.251]  -> xdg_toplevel@24.set_max_size(0, 0)
[2438129.263]  -> xdg_toplevel@24.set_fullscreen(wl_output@14)
[2438129.271] xdg_surface@23.configure(18349)
[2438129.279]  -> wl_surface@18.set_buffer_scale(1)
[2438129.288]  -> wl_compositor@5.create_region(new id wl_region@32)
[2438129.298]  -> wl_region@32.add(0, 0, 815, 739)
[2438129.318]  -> wl_surface@18.set_opaque_region(wl_region@32)
[2438129.326]  -> wl_region@32.destroy()
[2438129.332]  -> xdg_surface@23.set_window_geometry(0, 0, 815, 739)
[2438129.351]  -> xdg_surface@23.ack_configure(18349)
[2438129.505] wl_buffer@28.release()
[2438129.527] wl_callback@22.done(18349)
[2438130.121]  -> wl_surface@18.attach(wl_buffer@28, 0, 0)
[2438130.147]  -> wl_surface@18.damage(0, 0, 2147483647, 2147483647)
[2438130.252]  -> wl_surface@18.commit()
[2438130.261]  -> wl_display@1.sync(new id wl_callback@22)
[2438131.171] wl_display@1.delete_id(32)
[2438131.193] wl_display@1.delete_id(22)
[2438131.203] xdg_toplevel@24.configure(815, 739, array[8])
[2438131.222]  -> xdg_toplevel@24.set_min_size(0, 0)
[2438131.234]  -> xdg_toplevel@24.set_max_size(0, 0)
[2438131.246]  -> xdg_toplevel@24.set_fullscreen(wl_output@14)
```

Also, toggling fullscreen multiple times on these games crashes river. Panic log:
```
/home/naakka/zig-linux-x86_64-0.9.0/lib/std/debug.zig:224:14: 0x21c3d8 in std.debug.assert (river)
    if (!ok) unreachable; // assertion failure
             ^
/home/naakka/river/river/LayoutDemand.zig:135:11: 0x28242b in LayoutDemand.apply (river)
    assert(i == self.view_boxen.len);
          ^
/home/naakka/river/river/Layout.zig:156:76: 0x2812fe in Layout.handleRequest (river)
                if (layout_demand.serial == req.serial) layout_demand.apply(self);
                                                                           ^
/home/naakka/river/zig-cache/zig-wayland/common.zig:101:76: 0x282b78 in .wayland.common.Dispatcher(.wayland.river_layout_v3_server.LayoutV3,*Layout).dispatcher (river)
                    @ptrCast(fn (*Obj, Payload, Data) void, implementation)(
                                                                           ^
???:?:?: 0x7ffff7f47577 in ??? (???)
???:?:?: 0x7ffff7f40380 in ??? (???)
???:?:?: 0x7ffff7f43aac in ??? (???)
???:?:?: 0x7ffff7f44ff7 in ??? (???)
???:?:?: 0x7ffff7f41951 in ??? (???)
/home/naakka/river/river/main.zig:127:25: 0x21e338 in main (river)
    server.wl_server.run();
                        ^
/home/naakka/zig-linux-x86_64-0.9.0/lib/std/start.zig:553:37: 0x254457 in std.start.callMain (river)
            const result = root.main() catch |err| {
                                    ^
/home/naakka/zig-linux-x86_64-0.9.0/lib/std/start.zig:495:12: 0x221ef7 in std.start.callMainWithArgs (river)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/home/naakka/zig-linux-x86_64-0.9.0/lib/std/start.zig:460:12: 0x221ca2 in std.start.main (river)
    return @call(.{ .modifier = .always_inline }, callMainWithArgs, .{ @intCast(usize, c_argc), c_argv, envp });
           ^
???:?:?: 0x7ffff7b957ec in ??? (???)
```

**Comment by vainiovano** [comment]
It crashes with 100% reliability when running weston-simple-shm with this patch:
```diff
diff --git a/clients/simple-shm.c b/clients/simple-shm.c
index 1c2bea9e..8a2c45b7 100644
--- a/clients/simple-shm.c
+++ b/clients/simple-shm.c
@@ -147,6 +147,7 @@ handle_xdg_toplevel_configure(void *data, struct xdg_toplevel *xdg_toplevel,
                              int32_t width, int32_t height,
                              struct wl_array *state)
 {
+       xdg_toplevel_set_fullscreen(xdg_toplevel, NULL);
 }
 
 static void
```

**Comment by ifreund** [comment]
Excellent, that will make debugging this much easier thanks.

**Comment by ifreund** [comment]
The crash is fixed by be870e058d7929e332d8d2d7f1eb8600480b39dc.

Haven't had a chance to look into the behavior of those SDL programs yet, perhaps that is fixed as well.

**Comment by vainiovano** [comment]
The weird SDL behavior still exists. Here's a trace from gdb, showing `self.current` and `self.pending` for `View.applyPending` and `self.view.pending` and `event` for `XdgToplevel.handleRequestFullscreen`, fullscreen size is 678x739:

```
(DDNet is started with fullscreen enabled)

Thread 1 "river" hit Breakpoint 2, XdgToplevel.handleRequestFullscreen (listener=0xaa3670, event=0x7fffffffda90) at XdgToplevel.zig:332
332	   if (self.view.pending.fullscreen != event.fullscreen) {
$1 = {box = {x = 2, y = 27, width = 402, height = 710}, tags = 1, focus = 1, float = false, fullscreen = false, urgent = false}
$2 = {surface = 0xa7f220, fullscreen = true, output = 0xa36b80}

Thread 1 "river" hit Breakpoint 1, View.applyPending (self=0xaa35b0) at View.zig:174
174	   if (self.current.float and !self.pending.float) {
$3 = {box = {x = 2, y = 27, width = 402, height = 710}, tags = 1, focus = 1, float = false, fullscreen = false, urgent = false}
$4 = {box = {x = 2, y = 27, width = 402, height = 710}, tags = 1, focus = 1, float = false, fullscreen = true, urgent = false}
debug(layout): starting layout demand 'rivertile' on output 'WL-1'
debug(cursor): focused client set cursor

Thread 1 "river" hit Breakpoint 2, XdgToplevel.handleRequestFullscreen (listener=0xaa3670, event=0x7fffffffda90) at XdgToplevel.zig:332
332	   if (self.view.pending.fullscreen != event.fullscreen) {
$5 = {box = {x = 0, y = 0, width = 678, height = 739}, tags = 1, focus = 1, float = false, fullscreen = true, urgent = false}
$6 = {surface = 0xa7f220, fullscreen = true, output = 0xa36b80}

Thread 1 "river" hit Breakpoint 2, XdgToplevel.handleRequestFullscreen (listener=0xaa3670, event=0x7fffffffda90) at XdgToplevel.zig:332
332	   if (self.view.pending.fullscreen != event.fullscreen) {
$7 = {box = {x = 0, y = 0, width = 678, height = 739}, tags = 1, focus = 1, float = false, fullscreen = true, urgent = false}
$8 = {surface = 0xa7f220, fullscreen = true, output = 0xa36b80}
debug(cursor): focused client set cursor
debug(layout): layout 'rivertile' on output 'WL-1' pushed view dimensions: 0 0 678 714
debug(layout): layout 'rivertile' on output 'WL-1' commited
debug(transaction): started transaction with 1 pending configure(s)

(window is unfullscreened here)

Thread 1 "river" hit Breakpoint 1, View.applyPending (self=0xaa35b0) at View.zig:174
174	   if (self.current.float and !self.pending.float) {
$9 = {box = {x = 0, y = 0, width = 678, height = 739}, tags = 1, focus = 1, float = false, fullscreen = true, urgent = false}
$10 = {box = {x = 0, y = 0, width = 678, height = 739}, tags = 1, focus = 1, float = false, fullscreen = false, urgent = false}
debug(layout): starting layout demand 'rivertile' on output 'WL-1'
debug(layout): layout 'rivertile' on output 'WL-1' pushed view dimensions: 0 0 406 714
debug(layout): layout 'rivertile' on output 'WL-1' pushed view dimensions: 406 0 272 714
debug(layout): layout 'rivertile' on output 'WL-1' commited
debug(transaction): started transaction with 2 pending configure(s)

Thread 1 "river" hit Breakpoint 2, XdgToplevel.handleRequestFullscreen (listener=0xaa3670, event=0x7fffffffda90) at XdgToplevel.zig:332
332	   if (self.view.pending.fullscreen != event.fullscreen) {
$11 = {box = {x = 2, y = 27, width = 402, height = 710}, tags = 1, focus = 1, float = false, fullscreen = false, urgent = false}
$12 = {surface = 0xa7f220, fullscreen = true, output = 0xa36b80}

Thread 1 "river" hit Breakpoint 1, View.applyPending (self=0xaa35b0) at View.zig:174
174	   if (self.current.float and !self.pending.float) {
$13 = {box = {x = 0, y = 0, width = 678, height = 739}, tags = 1, focus = 1, float = false, fullscreen = true, urgent = false}
$14 = {box = {x = 2, y = 27, width = 402, height = 710}, tags = 1, focus = 1, float = false, fullscreen = true, urgent = false}
debug(layout): starting layout demand 'rivertile' on output 'WL-1'

Thread 1 "river" hit Breakpoint 2, XdgToplevel.handleRequestFullscreen (listener=0xaa3670, event=0x7fffffffda90) at XdgToplevel.zig:332
332	   if (self.view.pending.fullscreen != event.fullscreen) {
$15 = {box = {x = 2, y = 27, width = 402, height = 710}, tags = 1, focus = 1, float = false, fullscreen = true, urgent = false}
$16 = {surface = 0xa7f220, fullscreen = true, output = 0xa36b80}
debug(layout): layout 'rivertile' on output 'WL-1' pushed view dimensions: 0 0 678 714
debug(layout): layout 'rivertile' on output 'WL-1' commited
debug(transaction): started transaction with 1 pending configure(s)

Thread 1 "river" hit Breakpoint 2, XdgToplevel.handleRequestFullscreen (listener=0xaa3670, event=0x7fffffffda90) at XdgToplevel.zig:332
332	   if (self.view.pending.fullscreen != event.fullscreen) {
$17 = {box = {x = 2, y = 27, width = 402, height = 710}, tags = 1, focus = 1, float = false, fullscreen = true, urgent = false}
$18 = {surface = 0xa7f220, fullscreen = true, output = 0xa36b80}

Thread 1 "river" hit Breakpoint 2, XdgToplevel.handleRequestFullscreen (listener=0xaa3670, event=0x7fffffffda90) at XdgToplevel.zig:332
332	   if (self.view.pending.fullscreen != event.fullscreen) {
$19 = {box = {x = 2, y = 27, width = 402, height = 710}, tags = 1, focus = 1, float = false, fullscreen = true, urgent = false}
$20 = {surface = 0xa7f220, fullscreen = true, output = 0xa36b80}

(continues like this forever)
```

**Comment by ifreund** [comment]
Thanks for that excellent gdb log @vainiovano, this should be fixed by 147d9c2f90fc4a778d48d1517fc784a0809c51cb
