### ISSUE TITLE
Right Click Menu not working correctly in XWayland apps

### ISSUE THREAD

**Issue by andi-makes** [riverwm/river#620]
Since commit 7b554bd the right click Menu in Apps run through XWayland doesn't work anymore.

Apps where I can verify the right click menu not working:
 - IntelliJ IDEA: Upon a right click, the menu flashes for a really short time and closes itself immediately afterwards.
 - VS Code: The right click menu appears, stays, but when you try to select an entry you "click through" the right click menu, as if it wasn't there
 - KiCAD: Same behavior as VS Code
 
I verified that those apps were running through XWayland using `xeyes`.

Something to note: On Discord, the problem doesn't exist, even though it also is run through XWayland.

**Comment by Leon-Plickat** [comment]
> Something to note: On Discord, the problem doesn't exist, even though it also is run through XWayland.

One of the many *great* things about X11 is that there are many different hacky ways to do the exact same thing and you can be sure that for each way there is at least one popular application that implements it.

Do you happen to know whether this issue also exists in Sway?

**Comment by andi-makes** [comment]
Tested it with sway 1.7 (most recent version in the Arch Repos), this issue doesn't exist in sway.

**Comment by tleydxdy** [comment]
can confirm, right click menus and drop down boxes stopped working on my browser (brave). using keyboard to select the options work, so I'm suspecting it have something to do with how the mouse is handled

**Comment by zakvf** [comment]
This was my mistake when handling focus for override redirect Xwayland windows in the linked commit (https://github.com/riverwm/river/commit/7b554bde684b346aa5b307933f14277b0a6a7810). It should (hopefully) be fixed in https://github.com/riverwm/river/pull/624.

**Comment by andi-makes** [comment]
I can confirm that #624 fixes the "click through" issues as seen with VS Code and KiCAD, thank you very much!

But the "right click menu disappears immediately" issue with IntelliJ wasn't fixed unfortunately. Should I open up a separate Issue for this? I feel like it could have something to do with Java AWT/Swing's way to create right click Menus, I'll see if I can code up something small with the same issue later today.

**Comment by ifreund** [comment]
Looks like there is still an outstanding issue with IntelliJ, not sure if that's a regression or not but it's still a bug if it works in sway but not in river.

**Comment by zakvf** [comment]
> Looks like there is still an outstanding issue with IntelliJ, not sure if that's a regression or not but it's still a bug if it works in sway but not in river.

Apologies about that; I did not get around to mentioning it in the PR as I was hoping to look into the issue a bit more first. I think @andi-makes' problem with the IntelliJ popups is related with this wlroots issue: https://github.com/swaywm/wlroots/issues/2604. Because of that, I am trying to implement the ICCCM input model for focus instead of the heuristic used before and will see if that works.

**Comment by ifreund** [comment]
> Apologies about that; I did not get around to mentioning it in the PR as I was hoping to look into the issue a bit more first.

No worries at all! Thanks for taking a look at it, Xwayland support is probably the part of river I personally enjoy working on the least, I started writing a Wayland compositor because I *didn't* want to deal with X11 :D

**Comment by sitepodmatt** [comment]
Is this related https://github.com/Alexays/Waybar/issues/1494

**Comment by ifreund** [comment]
> Is this related [Alexays/Waybar#1494](https://github.com/Alexays/Waybar/issues/1494)

Almost certainly not, waybar isn't running through Xwayland.

**Comment by zakvf** [comment]
@andi-makes Could you try the following patch on your system? It fixes the IDEA issues on my end, but I do not know my way around IDEA and would like to see if there are any other problems that might be present. (I have one problem in particular, but it is inconsistent and could be unrelated: Sometimes, the drop-down menus on the 'Customize' page of the initial screen disappear after the mouse button is released, which is rectified after moving the application window.)

As a side note, I have kept the `overrideRedirectWantsFocus()` checks because the right-click menus in (Xwayland) Firefox break otherwise (like in the original issue).

	diff --git a/river/Cursor.zig b/river/Cursor.zig
	index 4557bad..f66d2be 100644
	--- a/river/Cursor.zig
	+++ b/river/Cursor.zig
	@@ -317,7 +317,9 @@ fn handleButton(listener: *wl.Listener(*wlr.Pointer.event.Button), event: *wlr.P
             	     },
             	     .xwayland_override_redirect => |override_redirect| {
                 	 if (!build_options.xwayland) unreachable;
	-                if (override_redirect.xwayland_surface.overrideRedirectWantsFocus()) {
	+                if (override_redirect.xwayland_surface.overrideRedirectWantsFocus() and
	+                    override_redirect.xwayland_surface.icccmInputModel() != .none)
	+                {
                     	     self.seat.setFocusRaw(.{ .xwayland_override_redirect = override_redirect });
                 	 }
             	     },
	diff --git a/river/XwaylandOverrideRedirect.zig b/river/XwaylandOverrideRedirect.zig
	index a6916ec..77cd74b 100644
	--- a/river/XwaylandOverrideRedirect.zig
	+++ b/river/XwaylandOverrideRedirect.zig
	@@ -96,7 +96,9 @@ pub fn handleMap(listener: *wl.Listener(*wlr.XwaylandSurface), xwayland_surface:
 	 
     	     xwayland_surface.surface.?.events.commit.add(&self.commit);
 	 
	-    if (self.xwayland_surface.overrideRedirectWantsFocus()) {
	+    if (self.xwayland_surface.overrideRedirectWantsFocus() and
	+        self.xwayland_surface.icccmInputModel() != .none)
	+    {
         	 server.input_manager.defaultSeat().setFocusRaw(.{ .xwayland_override_redirect = self });
     	     }
 	 }

**Comment by andi-makes** [comment]
Thank you very much, the patch works!

Regarding the `Customize` page dropdown issue, I've found a way to reliably recreate it:
 - Choose anything in the dropdown menu
 - Open it up again, now the cursor highlighting seems offset and it is doing weird stuff

And it indeed only happens in the first initial screen, maybe it is some IntelliJ internal bug?

This seems to be another unrelated issue though, because I did briefly try it in sway, and the issue also exists there.

Again, thank you very much for the patch!

**Comment by zakvf** [comment]
> Thank you very much, the patch works!

Awesome! Thanks for testing it.


> And it indeed only happens in the first initial screen, maybe it is some IntelliJ internal bug?
>
> This seems to be another unrelated issue though, because I did briefly try it in sway, and the issue also exists there.

Okay, then, I think I will leave it there for now as I know very little about IntelliJ, and I am not sure where the issue might be in river if it is actually a problem on the compositor's side.

I will make a PR with the patch in a few days if there are no more issues on your end.

**Comment by Bonicgamer** [comment]
qpwgraph, zoom, qt5ct, and qt6ct running in xwayland with QT_QPA_PLATFORM=xcb still has issues for me. I don't know whether it's enough of an issue to reopen this issue, or if it could be looked over since they work fine running natively under wayland (besides zoom).

I also don't have any issues with Dolphin Emu or PolyMc so I don't know if it's just a Qt thing.

**Comment by Bonicgamer** [comment]
> Are you saying there's still a regression in those programs since recent Xwayland changes? Or did those programs never work properly under river's Xwayland and still don't work?

Yes, I'm talking about the recent Xwayland changes.

> I'm not really sympathetic to running potentially Wayland native qt programs under Xwayland. The only reason for Xwayland to exist is so that programs without a native Wayland backend may still be used.

Yeah, I understand. The only reason why I brought it up was that it could effect other applications that don't have a native Wayland backend and fixing these applications might help those hypothetical applications.

> Anyhow, if there are broken Xwayland programs that are important to you please open a new issue with a description of what isn't working and if it ever worked on a previous river version.

Since I can just use the web version of Zoom, it not important for me to get the one menu in the native version to work. If/Once there is an application that I need that isn't working properly, I will go and do that :+1:
