### ISSUE TITLE
Dropdown Issue with Reaper DAW (Similar issue to this one documented in Sway)

### ISSUE THREAD

**Issue by ma7thmaster** [riverwm/river#723]
I am getting a similar issue while using Reaper DAW where the dropdown immediately disappears after clicking the toolbar in Reaper.
https://github.com/swaywm/sway/issues/6324#issue-919573975[](url)

**Comment by ma7thmaster** [comment]
Looks like this is the relevant Sway fix.
https://github.com/swaywm/sway/pull/6461

**Comment by ifreund** [comment]
Related: 
- https://github.com/swaywm/sway/pull/6764
- #638

**Comment by hkva** [comment]
This also seems to affect menu bars in Wine applications.

Here's a minimal Win32 program that showcases the bug, in case installing mingw+wine is more convenient than installing Reaper:
```c
// Compile with x86_64-w64-mingw32-gcc -o example example.c
#include <windows.h>

#define TITLE "River dropdown bug example"

int WINAPI WinMain(HINSTANCE hInst, HINSTANCE hPrev, LPSTR nCmdLine, int nShow) {
    WNDCLASS wc = { 0, DefWindowProc, 0, 0, 0, 0, 0, 0, 0, TITLE };
    RegisterClass(&wc);

    HWND hWnd = CreateWindowEx(0, TITLE, TITLE, WS_VISIBLE, CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT, NULL, NULL, hInst, NULL);
    if (!hWnd) {
        return -1;
    }

    HMENU hBar  = CreateMenu();
    HMENU hMenu = CreateMenu();
    AppendMenu(hMenu, MF_STRING, 0, "Quit");
    AppendMenu(hBar, MF_POPUP, (UINT_PTR)hMenu, "File");
    SetMenu(hWnd, hBar);

    ShowWindow(hWnd, nShow);

    MSG msg;
    while (GetMessage(&msg, NULL, 0, 0) > 0) {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }
}
```

**Comment by zakvf** [comment]
@hkva I believe dropdown menus in Wine applications are a separate issue, which can be fixed with the following patch.
```
diff --git a/river/Cursor.zig b/river/Cursor.zig
index 24aa5a1..c794554 100644
--- a/river/Cursor.zig
+++ b/river/Cursor.zig
@@ -369,7 +369,8 @@ fn updateKeyboardFocus(self: Self, result: SurfaceAtResult) void {
         .xwayland_override_redirect => |override_redirect| {
             if (!build_options.xwayland) unreachable;
             if (override_redirect.xwayland_surface.overrideRedirectWantsFocus() and
-                override_redirect.xwayland_surface.icccmInputModel() != .none)
+                override_redirect.xwayland_surface.icccmInputModel() != .none and
+                override_redirect.xwayland_surface.icccmInputModel() != .global)
             {
                 self.seat.setFocusRaw(.{ .xwayland_override_redirect = override_redirect });
             }
diff --git a/river/XwaylandOverrideRedirect.zig b/river/XwaylandOverrideRedirect.zig
index 6b61100..a2517a9 100644
--- a/river/XwaylandOverrideRedirect.zig
+++ b/river/XwaylandOverrideRedirect.zig
@@ -98,7 +98,8 @@ pub fn handleMap(listener: *wl.Listener(*wlr.XwaylandSurface), xwayland_surface:
     xwayland_surface.surface.?.events.commit.add(&self.commit);

     if (self.xwayland_surface.overrideRedirectWantsFocus() and
-        self.xwayland_surface.icccmInputModel() != .none)
+        self.xwayland_surface.icccmInputModel() != .none and
+        self.xwayland_surface.icccmInputModel() != .global)
     {
         server.input_manager.defaultSeat().setFocusRaw(.{ .xwayland_override_redirect = self });
     }
```
I am not sure if this is a proper solution, however; other programs might break because the global [ICCCM input model](https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.7) still expects input, despite not wanting focus to be set on the program's windows. (I find the input model's description confusing.)

**Comment by ifreund** [comment]
This should be fixed for reaper at least by #638

**Comment by ma7thmaster** [comment]
I'm using River 0.2.1-1 (Latest version on AUR now) and the issue still occurs. There's nothing on the changelog for 0.2.2 differences other than the Zig versioning, or was the fixed branch merged into master before 0.2.2 was sent out?

**Comment by novakne** [comment]
This was merged after 0.2.2. You need to use the master branch or wait for a next release

**Comment by ma7thmaster** [comment]
Understood. Thanks for the clarification!
